spring:
  application:
    name: Coupon_Service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/Coupon_DB
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:421605}

server:
  port: 9097
